version: '3.8'

services:
  db:
    build: ./smartsoftlabs/PostgreSQL
    restart: always
    ports:
      - '5432:5432'
    hostname: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - postgres
volumes:
  database_data:
    driver: local
networks:
  postgres:
    driver: bridge
