version: '3.8'

services:
  db:
    build: ./smartsoftlabs/PostgreSQL
    restart: always
    ports:
      - '5432:5432'
    hostname: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - postgres
      - nginx-api-net
  nginx-api:
    build:
      context: ./nginx
    container_name: nginx-nest-api
    hostname: nginx
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - nginx-api-net
  redis:
    image: 'redis:6.0.9-alpine'
    container_name: redis-nest
    mem_limit: 512m
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
volumes:
  database_data:
    driver: local
  redis:
    driver: local
networks:
  postgres:
    driver: bridge
  nginx-api-net:
    driver: bridge
